name: instadam
description: A minimal Instagram-like Flutter app example (InstaDAM)
publish_to: 'none'
version: 0.0.1
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.8+4
  path_provider: ^2.0.14
  path: ^1.8.3
  intl: ^0.18.1
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
